### ISSUE TITLE
Bot antwortet nicht

### ISSUE THREAD

**Issue by hacker-h** [Nickkr/IWIbot#16]
Auf viele Fragen/Aussagen antwortet der Bot garnicht oder falsch:
Wie spät ist es? -> keine antwort
Was ist Sprache? -> OpenWhiskError: Unknown Error From API: socket hang up

Du Penner ->Für welches von folgenden Angebote interessierst du dich: Wahlessen 1, Wahlessen 2, Aktionstheke, Gut und Günstig, Buffet oder Schnitzelbar?

**Comment by Voldemord92** [comment]
Jetzt läuft er wieder. Muss halt für gute Antworten trainiert werden..
